# docker-compose file to run a postgres container
services:
  timeseries_db:
    container_name: timeseries_db
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      # SELinux blocks containers from reading some mounted files. 
      # :Z flag relabels the file in the shared volume with a "shared" object type
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:Z
      # enable persistent data
      - timeseries_data:/var/lib/postgresql/data

volumes:
  # create a named volume to persist data
  timeseries_data:
    name: timeseries_data
